utils::globalVariables(
    c(
        "_primary_disease",
        "<<-",
        "avg_High",
        "avg_Low",
        "cell_type",
        "cells",
        "genes_1",
        "genes_2",
        "genes_3",
        "high",
        "High - Low",
        "metadata",
        "p.adj",
        "p.adj.signif",
        "phenotypes",
        "sd_High",
        "sd_Low",
        "stats",
        "tcga",
        "value"
    )
)
